### ISSUE TITLE
move from hassbian to opensuse

### ISSUE THREAD

**Issue by trixpan** [home-assistant/pi-gen#9]
hi,

have you considered moving from raspbian to opensuse? SuSe's ARM HCL, while reasonably unknown, supports a myriad of systems mostly using mainstream kernel.

https://en.opensuse.org/openSUSE:OpenSUSE_on_your_ARM_board

PS-This is not a distro bake-off post. I just suggesting based on my experience dealing with both AllWinner and RPi based boards.

**Comment by Landrash** [comment]
Since I'm the one currently maintaining it I doubt I will move it over to OpenSUSE since I personally use Arch and Debian systems. The first draft of my image that I didn't share was actually a Arch image but choose to go Raspbian for the general support and amount of documentation.

I'll have a look at the link you provided but currently HASSbian won't change to openSUSE.
